name: Bug report
description: Create a report to help us improve
type: Bug
assignees:
  - sephiroth-j
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: input
    attributes:
      label: Plugin Version
    validations:
      required: true

  - type: input
    attributes:
      label: Jenkins Version
    validations:
      required: true

  - type: input
    attributes:
      label: Java Version for Jenkins
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Type of Jenkins Job
      options:
        - classic (I use the ui to configure the job)
        - declarative pipeline
        - scripted pipeline
    validations:
      required: true

  - type: input
    attributes:
      label: Dependency-Track Version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the behavior
      description: A clear and concise description of what the bug is.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here (screenshots, logs, etc.).
    validations:
      required: false
